version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/functions'
    schedule:
      interval: 'monthly'
      time: '04:00'
    labels:
      - dependencies
    allow:
      - dependency-name: 'firebase-admin'
      - dependency-name: 'firebase-functions'
      - dependency-name: 'meilisearch'
